import Box from '@/shared/Box'
import InputWithLabel from '@/shared/InputWithLabel/InputWithLabel'
import NavBar from '@/shared/NavBar/NavBar'
import Head from 'next/head'
import Image from 'next/image'
import { useMediaQuery } from 'react-responsive'

export default function Home() {
  const isLaptop = useMediaQuery({
    query: '(min-width: 600px)'
  })
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <NavBar />
        <Box css={{'padding':'.7rem'}}>
        {
          !isLaptop?
          <InputWithLabel />:''
        }

        </Box>
      </Box>
    </>
  )
}
