import Box from '@/shared/Box'
import Category from '@/shared/Category/Category'
import InputWithLabel from '@/shared/InputWithLabel/InputWithLabel'
import NavBar from '@/shared/NavBar/NavBar'
import Head from 'next/head'
import Image from 'next/image'
import { useMediaQuery } from 'react-responsive'
import {BsFillHouseFill} from 'react-icons/bs'
import {GiAfrica} from 'react-icons/gi'
import {FaCarrot} from 'react-icons/fa'
import {MdOutlineNoDrinks}  from 'react-icons/md'
import ResturantCard from '@/shared/ResturantCard/ResturantCard'
export default function Home() {
  const isLaptop = useMediaQuery({
    query: '(min-width: 600px)'
  })
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <NavBar />
        <Box css={{'padding':'.7rem'}}>
        {
          !isLaptop?
          <InputWithLabel />:''
        }

        {/* this is where the index code start take the code above to a layout */}
        <br /><br />
        <Box>
            <h2>Explore Categories</h2>
          <br />
          <Box css={{
            'maxWidth':'600px','display':'flex','justifyContent':'space-between',
            'overflowX':'auto',
            'gap':'30px'
        }}>
        <Category 
          title='Restaurants'
          icon={<BsFillHouseFill/>}
        />
         <Category 
            title='African Meals'
            icon={<GiAfrica style={{'color':'#115442'}}/>}
            color='yellow'
            />
         <Category 
            title='Fit Fam'
            color='green'

          icon={<FaCarrot style={{'color':'#eb5d3d'}}/>}
        />
         <Category 
        title='Drinks'
        color='yellow2'

          icon={<MdOutlineNoDrinks style={{'color':'#e9841a'}}/>}
        />

        
          </Box>
        </Box>
        <br />
        <br />
        <h2>All Restaurants</h2>
        <br />
        <Box css={{'display':'flex','flexWrap':'wrap','gap':'20px'}}>
          {
            [...new Array(10)].map((d,index)=>(
              <ResturantCard  key={index}/>
            ))
          }
        </Box>
        </Box>
      </Box>
    </>
  )
}
